# Generated by Django 4.2.4 on 2023-08-31 10:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("products", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="product",
            name="custom_code",
            field=models.CharField(max_length=20, verbose_name="Custom Product Code"),
        ),
    ]
