# Generated by Django 4.2.4 on 2023-08-31 17:53

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ("products", "0005_alter_country_name"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="country",
            name="trade_choice",
        ),
        migrations.AddField(
            model_name="trade",
            name="trade_choice",
            field=models.CharField(
                choices=[("Import From", "Import From"), ("Export To", "Export To")],
                default=django.utils.timezone.now,
                max_length=50,
            ),
            preserve_default=False,
        ),
    ]
